version: '3'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - '5435:5432'
    container_name: 'pgsql'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:  
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  pg-data: